import { useEffect, useRef, useState } from "react";
import { getLocalizedAsset } from "../../content/educationContent";

export function VideoPlayer({ item, language, copy }) {
  const [requested, setRequested] = useState(false);
  const video = item.video;
  const localMediaUrl = typeof item.mediaUrl === "string"
    && item.mediaUrl.startsWith("/")
    && !item.mediaUrl.startsWith("//")
    ? item.mediaUrl
    : null;
  const isApprovedHost = video?.provider === "youtube" && /^[A-Za-z0-9_-]{11}$/.test(video.id || "");
  const externalUrl = isApprovedHost
    ? `https://www.youtube.com/watch?v=${encodeURIComponent(video.id)}`
    : null;
  const embedUrl = isApprovedHost
    ? `https://www.youtube-nocookie.com/embed/${encodeURIComponent(video.id)}?rel=0`
    : null;

  return (
    <section className="education-video" aria-label={item.translations[language].title}>
      {localMediaUrl ? (
        <video className="education-video-frame" controls preload="none" poster={item.thumbnail}>
          <source src={localMediaUrl} />
          {(video?.captionTracks || []).map((track) => (
            <track
              key={track.src}
              kind="captions"
              src={track.src}
              srcLang={track.language}
              label={track.label}
              default={track.language === language}
            />
          ))}
        </video>
      ) : requested && embedUrl ? (
        <iframe
          className="education-video-frame"
          title={item.translations[language].title}
          src={embedUrl}
          loading="lazy"
          allow="encrypted-media; picture-in-picture; web-share"
          allowFullScreen
        />
      ) : (
        <div className="education-video-poster">
          <img
            src={getLocalizedAsset(item.thumbnail, language)}
            alt={item.altText[language]}
            loading="lazy"
          />
          {embedUrl && (
            <button className="btn primary" type="button" onClick={() => setRequested(true)}>
              {copy.videoLoad}
            </button>
          )}
        </div>
      )}
      <p className="education-media-note">{copy.videoPrivacy}</p>
      <p className="education-media-note">{copy.videoAudio}</p>
      {externalUrl && (
        <a href={externalUrl} target="_blank" rel="noreferrer" className="education-external-link">
          {copy.externalVideo} <span aria-hidden="true">↗</span>
        </a>
      )}
    </section>
  );
}

export function AudioPlayer({ text, language, copy }) {
  const [playing, setPlaying] = useState(false);
  const [paused, setPaused] = useState(false);
  const [message, setMessage] = useState("");
  const utteranceRef = useRef(null);

  useEffect(() => () => {
    if (typeof window !== "undefined" && window.speechSynthesis) {
      window.speechSynthesis.cancel();
    }
  }, []);

  const stop = () => {
    window.speechSynthesis?.cancel();
    utteranceRef.current = null;
    setPlaying(false);
    setPaused(false);
  };

  const play = () => {
    if (!window.speechSynthesis || typeof window.SpeechSynthesisUtterance === "undefined") {
      setMessage(copy.audioUnavailable);
      return;
    }
    stop();
    const utterance = new window.SpeechSynthesisUtterance(text);
    utterance.lang = language === "sw" ? "sw-KE" : "en-KE";
    utterance.rate = 0.92;
    utterance.onend = () => {
      utteranceRef.current = null;
      setPlaying(false);
      setPaused(false);
    };
    utterance.onerror = () => {
      utteranceRef.current = null;
      setPlaying(false);
      setPaused(false);
      setMessage(copy.audioUnavailable);
    };
    utteranceRef.current = utterance;
    setMessage("");
    setPlaying(true);
    window.speechSynthesis.speak(utterance);
  };

  const togglePlayback = () => {
    if (!playing) {
      play();
    } else if (paused) {
      window.speechSynthesis.resume();
      setPaused(false);
    } else {
      window.speechSynthesis.pause();
      setPaused(true);
    }
  };

  return (
    <div className="education-audio">
      <div className="education-audio-controls">
        <span className="education-audio-icon" aria-hidden="true">◉</span>
        <div>
          <strong>{language === "sw" ? "Somo la sauti la Jalia" : "Jalia audio lesson"}</strong>
          <p>{language === "sw" ? "Sauti hutolewa na kifaa chako." : "Audio is generated by your device."}</p>
        </div>
        <button className="btn primary" type="button" onClick={togglePlayback} aria-pressed={playing && !paused}>
          {playing ? (paused ? copy.audioResume : copy.audioPause) : copy.audioPlay}
        </button>
        {playing && <button className="btn secondary" type="button" onClick={stop}>{copy.audioStop}</button>}
      </div>
      {message && <p className="education-inline-status" role="status">{message}</p>}
    </div>
  );
}
