import {
  CalendarIcon, FlaskIcon, MessageIcon, PulseIcon, DocumentIcon, CheckIcon, HandoffIcon,
} from "../components/Icons";

export const EVENT_META = {
  appointment: { label: "Appointment", icon: CalendarIcon, chip: "chip-primary" },
  medication: { label: "Medication", icon: FlaskIcon, chip: "chip-accent" },
  observation: { label: "Observation", icon: PulseIcon, chip: "chip-warning" },
  communication: { label: "Communication", icon: MessageIcon, chip: "chip-info" },
  task: { label: "Follow-up", icon: CheckIcon, chip: "chip-neutral" },
  result: { label: "Result", icon: FlaskIcon, chip: "chip-success" },
  document: { label: "Document", icon: DocumentIcon, chip: "chip-neutral" },
  handoff: { label: "Handoff", icon: HandoffIcon, chip: "chip-primary" },
};

export const SOURCE_LABEL = {
  voice: "Captured from voice note",
  photo: "Captured from photo",
  screenshot: "Captured from screenshot",
  upload: "Uploaded document",
  manual: "Entered manually",
  system: "Generated by Jalia",
};

export function formatWhen(iso) {
  if (!iso) return "";
  const d = new Date(iso);
  const now = new Date();
  const sameDay = d.toDateString() === now.toDateString();
  const time = d.toLocaleTimeString(undefined, { hour: "numeric", minute: "2-digit" });
  if (sameDay) return `Today · ${time}`;
  const yesterday = new Date(now);
  yesterday.setDate(now.getDate() - 1);
  if (d.toDateString() === yesterday.toDateString()) return `Yesterday · ${time}`;
  const tomorrow = new Date(now);
  tomorrow.setDate(now.getDate() + 1);
  if (d.toDateString() === tomorrow.toDateString()) return `Tomorrow · ${time}`;
  return `${d.toLocaleDateString(undefined, { month: "short", day: "numeric" })} · ${time}`;
}

export function dayLabel(iso) {
  const d = new Date(iso);
  const now = new Date();
  if (d.toDateString() === now.toDateString()) return "Today";
  const yesterday = new Date(now);
  yesterday.setDate(now.getDate() - 1);
  if (d.toDateString() === yesterday.toDateString()) return "Yesterday";
  return d.toLocaleDateString(undefined, { weekday: "long", month: "short", day: "numeric" });
}
